# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    branches:
      - release

# workflow tasks
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/arm, darwin/amd64, windows/amd64'
            package: 'src'
            name: 'image-sorter'
            compress: 'true'
            dest: 'dist'
      - uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true